### ISSUE TITLE
janusec: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vhostvn** [Janusec/janusec#19]
**Environment:**

- OS: CentOS Linux release 7.9.2009 (Core)
- DB: postgresql11-server-11.13-1PGDG.rhel7.x86_64
- Model:

**Node model:**

- 1 node primary: installed postgresql 11 / Domain: janu1.domain.com
- 2 slave node: no postgresql database / Domain: janu2.domain.com and janu3.domain.com

**Error 1**: on node janu2

`http: TLS handshake error from 51.15.189.176:58534: Unknown Host:`

**Error 2**: on node janu2

`Aug 22 20:23:00 janu2 systemd: janusec.service holdoff time over, scheduling restart.
Aug 22 20:23:00 janu2 systemd: Stopped Janusec Application Gateway.
Aug 22 20:23:00 janu2 systemd: Started Janusec Application Gateway.
Aug 22 20:23:00 janu2 janusec: panic: runtime error: invalid memory address or nil pointer dereference
Aug 22 20:23:00 janu2 janusec: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x96fd6d]
Aug 22 20:23:00 janu2 janusec: goroutine 28 [running]:
Aug 22 20:23:00 janu2 janusec: janusec/gateway.SyncTimeTick()
Aug 22 20:23:00 janu2 janusec: /data/program/janusec/gateway/rpc_update.go:26 +0x4d
Aug 22 20:23:00 janu2 janusec: created by main.main
Aug 22 20:23:00 janu2 janusec: /data/program/janusec/janusec.go:65 +0xf2b
Aug 22 20:23:00 janu2 systemd: janusec.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 22 20:23:00 janu2 systemd: Unit janusec.service entered failed state.
Aug 22 20:23:00 janu2 systemd: janusec.service failed.
Aug 22 20:23:00 janu2 systemd: janusec.service holdoff time over, scheduling restart.
Aug 22 20:23:00 janu2 systemd: Stopped Janusec Application Gateway.
Aug 22 20:23:00 janu2 systemd: start request repeated too quickly for janusec.service
Aug 22 20:23:00 janu2 systemd: Failed to start Janusec Application Gateway.
Aug 22 20:23:00 janu2 systemd: Unit janusec.service entered failed state.
Aug 22 20:23:00 janu2 systemd: janusec.service failed.
Aug 22 20:23:00 janu2 kdumpctl: kexec: loaded kdump kernel
Aug 22 20:23:00 janu2 kdumpctl: Starting kdump: [OK]
`

May I know how to fix this issues?

**Comment by vhostvn** [comment]
The root cause: time server out of sync
