### ISSUE TITLE
Occurrence of services error on replicated node

### ISSUE THREAD

**Issue by NgHuuAn** [Janusec/janusec#26]
Hi

We have installed 1 Primary node and 5 Replicated nodes from about a week ago with version 1.2.3. 

We have updated to version 1.2.5 from 2 days ago

+ 1 Primary node using CentOS 7, pgsql version 11
+ 5 Replicated node using CentOS 7

But today one node replicated encountered an issue. Although it was possible to fix it by restarting the janusec services but the sudden crashed led to instability. Can you help us check what the issue is and how to fix it?

Our logs are attached below. 

Messages Logs: 

```
Sep 19 11:49:45 server6 janusec: 2021/09/19 11:49:45 http: panic serving 66.249.79.117:50475: interface conversion: interface {} is nil, not *models.CCPolicy
Sep 19 11:49:45 server6 janusec: goroutine 564893 [running]:
Sep 19 11:49:45 server6 janusec: net/http.(*conn).serve.func1(0xc00025e000)
Sep 19 11:49:45 server6 janusec: /usr/local/go/src/net/http/server.go:1804 +0x153
Sep 19 11:49:45 server6 janusec: panic(0xa48040, 0xc0005a42d0)
Sep 19 11:49:45 server6 janusec: /usr/local/go/src/runtime/panic.go:971 +0x499
Sep 19 11:49:45 server6 janusec: janusec/firewall.GetCCPolicyByAppID(0x1f, 0xaf0a9e)
Sep 19 11:49:45 server6 janusec: /data/program/janusec/firewall/cc.go:97 +0xe5
Sep 19 11:49:45 server6 janusec: janusec/firewall.IsCCAttack(0xc0003aa600, 0xc00027d0a0, 0xc000074168, 0xd, 0xc6, 0x0, 0x22e, 0x673, 0xc0005bf3c8)
Sep 19 11:49:45 server6 janusec: /data/program/janusec/firewall/cc.go:114 +0x45
Sep 19 11:49:45 server6 janusec: janusec/gateway.ReverseHandlerFunc(0xbbf3d0, 0xc0000e60e0, 0xc0003aa600)
.....
Sep 19 12:51:34 server6 janusec: net/http.HandlerFunc.ServeHTTP(0xb23c80, 0xbbf310, 0xc0001b80b0, 0xc0002c6900)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:2049 +0x44
Sep 19 12:51:34 server6 janusec: net/http.(*ServeMux).ServeHTTP(0xc0000261c0, 0xbbf310, 0xc0001b80b0, 0xc0002c6900)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:2428 +0x1ad
Sep 19 12:51:34 server6 janusec: main.AddContextHandler.func1(0xbbf310, 0xc0001b80b0, 0xc0002c6800)
Sep 19 12:51:34 server6 janusec: /data/program/janusec/janusec.go:210 +0x1c7
Sep 19 12:51:34 server6 janusec: net/http.HandlerFunc.ServeHTTP(0xc0004bc4b0, 0xbbf310, 0xc0001b80b0, 0xc0002c6800)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:2049 +0x44
Sep 19 12:51:34 server6 janusec: golang.org/x/crypto/acme/autocert.(*Manager).HTTPHandler.func1(0xbbf310, 0xc0001b80b0, 0xc0002c6800)
Sep 19 12:51:34 server6 janusec: /home/U2/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210711020723-a769d52b0f97/acme/autocert/autocert.go:393 +0x8f
Sep 19 12:51:34 server6 janusec: net/http.HandlerFunc.ServeHTTP(0xc0000202e0, 0xbbf310, 0xc0001b80b0, 0xc0002c6800)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:2049 +0x44
Sep 19 12:51:34 server6 janusec: net/http.serverHandler.ServeHTTP(0xc000446000, 0xbbf310, 0xc0001b80b0, 0xc0002c6800)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:2867 +0xa3
Sep 19 12:51:34 server6 janusec: net/http.initALPNRequest.ServeHTTP(0xbc07c0, 0xc000539440, 0xc000643c00, 0xc000446000, 0xbbf310, 0xc0001b80b0, 0xc0002c6800)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:3439 +0x8d
Sep 19 12:51:34 server6 janusec: net/http.(*http2serverConn).runHandler(0xc0000a4d80, 0xc0001b80b0, 0xc0002c6800, 0xc00024a198)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/h2_bundle.go:5723 +0x8b
Sep 19 12:51:34 server6 janusec: created by net/http.(*http2serverConn).processHeaders
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/h2_bundle.go:5453 +0x505
Sep 19 12:51:34 server6 janusec: 2021/09/19 12:51:34 http2: panic serving 118.70.202.10:15506: interface conversion: interface {} is nil, not *models.CCPolicy
Sep 19 12:51:34 server6 janusec: goroutine 670532 [running]:
Sep 19 12:51:34 server6 janusec: net/http.(*http2serverConn).runHandler.func1(0xc0001b80b8, 0xc00090df8e, 0xc00084fe00)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/h2_bundle.go:5716 +0x193
Sep 19 12:51:34 server6 janusec: panic(0xa48040, 0xc0002671a0)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/runtime/panic.go:965 +0x1b9
Sep 19 12:51:34 server6 janusec: janusec/firewall.GetCCPolicyByAppID(0x1c, 0x13)
Sep 19 12:51:34 server6 janusec: /data/program/janusec/firewall/cc.go:97 +0xe5
Sep 19 12:51:34 server6 janusec: janusec/firewall.IsCCAttack(0xc000a82800, 0xc000447c00, 0xc00037c318, 0xd, 0x40, 0x60ea75, 0xc000379500, 0xbb47c0, 0xc00000e1e8)
Sep 19 12:51:34 server6 janusec: /data/program/janusec/firewall/cc.go:114 +0x45
Sep 19 12:51:34 server6 janusec: janusec/gateway.ReverseHandlerFunc(0xbbf310, 0xc0001b80b8, 0xc000a82800)
Sep 19 12:51:34 server6 janusec: /data/program/janusec/gateway/gateway.go:154 +0x3e95
Sep 19 12:51:34 server6 janusec: net/http.HandlerFunc.ServeHTTP(0xb23c80, 0xbbf310, 0xc0001b80b8, 0xc000a82800)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:2049 +0x44
Sep 19 12:51:34 server6 janusec: net/http.(*ServeMux).ServeHTTP(0xc0000261c0, 0xbbf310, 0xc0001b80b8, 0xc000a82800)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:2428 +0x1ad
Sep 19 12:51:34 server6 janusec: main.AddContextHandler.func1(0xbbf310, 0xc0001b80b8, 0xc0002c6b00)
Sep 19 12:51:34 server6 janusec: /data/program/janusec/janusec.go:210 +0x1c7
Sep 19 12:51:34 server6 janusec: net/http.HandlerFunc.ServeHTTP(0xc0004bc4b0, 0xbbf310, 0xc0001b80b8, 0xc0002c6b00)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:2049 +0x44
Sep 19 12:51:34 server6 janusec: golang.org/x/crypto/acme/autocert.(*Manager).HTTPHandler.func1(0xbbf310, 0xc0001b80b8, 0xc0002c6b00)
Sep 19 12:51:34 server6 janusec: /home/U2/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210711020723-a769d52b0f97/acme/autocert/autocert.go:393 +0x8f
Sep 19 12:51:34 server6 janusec: net/http.HandlerFunc.ServeHTTP(0xc0000202e0, 0xbbf310, 0xc0001b80b8, 0xc0002c6b00)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:2049 +0x44
Sep 19 12:51:34 server6 janusec: net/http.serverHandler.ServeHTTP(0xc000446000, 0xbbf310, 0xc0001b80b8, 0xc0002c6b00)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:2867 +0xa3
Sep 19 12:51:34 server6 janusec: net/http.initALPNRequest.ServeHTTP(0xbc07c0, 0xc0002662d0, 0xc0009eb880, 0xc000446000, 0xbbf310, 0xc0001b80b8, 0xc0002c6b00)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:3439 +0x8d
Sep 19 12:51:34 server6 janusec: net/http.(*http2serverConn).runHandler(0xc00084fe00, 0xc0001b80b8, 0xc0002c6b00, 0xc00024a780)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/h2_bundle.go:5723 +0x8b
Sep 19 12:51:34 server6 janusec: created by net/http.(*http2serverConn).processHeaders
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/h2_bundle.go:5453 +0x505
Sep 19 12:51:34 server6 janusec: 2021/09/19 12:51:34 http2: panic serving 207.46.13.129:61824: interface conversion: interface {} is nil, not *models.CCPolicy
Sep 19 12:51:34 server6 janusec: goroutine 670562 [running]:
Sep 19 12:51:34 server6 janusec: net/http.(*http2serverConn).runHandler.func1(0xc0000c45c0, 0xc000343f8e, 0xc00084f380)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/h2_bundle.go:5716 +0x193
Sep 19 12:51:34 server6 janusec: panic(0xa48040, 0xc000270450)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/runtime/panic.go:965 +0x1b9
Sep 19 12:51:34 server6 janusec: janusec/firewall.GetCCPolicyByAppID(0x1c, 0x13)
Sep 19 12:51:34 server6 janusec: /data/program/janusec/firewall/cc.go:97 +0xe5
Sep 19 12:51:34 server6 janusec: janusec/firewall.IsCCAttack(0xc00036c800, 0xc000447c00, 0xc00037c270, 0xd, 0x47, 0x60ea75, 0xc000379880, 0xbb47c0, 0xc0001b80c8)
Sep 19 12:51:34 server6 janusec: /data/program/janusec/firewall/cc.go:114 +0x45
Sep 19 12:51:34 server6 janusec: janusec/gateway.ReverseHandlerFunc(0xbbf310, 0xc0000c45c0, 0xc00036c800)
Sep 19 12:51:34 server6 janusec: /data/program/janusec/gateway/gateway.go:154 +0x3e95
Sep 19 12:51:34 server6 janusec: net/http.HandlerFunc.ServeHTTP(0xb23c80, 0xbbf310, 0xc0000c45c0, 0xc00036c800)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:2049 +0x44
Sep 19 12:51:34 server6 janusec: net/http.(*ServeMux).ServeHTTP(0xc0000261c0, 0xbbf310, 0xc0000c45c0, 0xc00036c800)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:2428 +0x1ad
Sep 19 12:51:34 server6 janusec: main.AddContextHandler.func1(0xbbf310, 0xc0000c45c0, 0xc00036c700)
Sep 19 12:51:34 server6 janusec: /data/program/janusec/janusec.go:210 +0x1c7
Sep 19 12:51:34 server6 janusec: net/http.HandlerFunc.ServeHTTP(0xc0004bc4b0, 0xbbf310, 0xc0000c45c0, 0xc00036c700)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:2049 +0x44
Sep 19 12:51:34 server6 janusec: golang.org/x/crypto/acme/autocert.(*Manager).HTTPHandler.func1(0xbbf310, 0xc0000c45c0, 0xc00036c700)
Sep 19 12:51:34 server6 janusec: /home/U2/go/pkg/mod/golang.org/x/crypto@v0.0.0-20210711020723-a769d52b0f97/acme/autocert/autocert.go:393 +0x8f
Sep 19 12:51:34 server6 janusec: net/http.HandlerFunc.ServeHTTP(0xc0000202e0, 0xbbf310, 0xc0000c45c0, 0xc00036c700)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:2049 +0x44
Sep 19 12:51:34 server6 janusec: net/http.serverHandler.ServeHTTP(0xc000446000, 0xbbf310, 0xc0000c45c0, 0xc00036c700)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:2867 +0xa3
Sep 19 12:51:34 server6 janusec: net/http.initALPNRequest.ServeHTTP(0xbc07c0, 0xc0009c8cf0, 0xc0009ea000, 0xc000446000, 0xbbf310, 0xc0000c45c0, 0xc00036c700)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/server.go:3439 +0x8d
Sep 19 12:51:34 server6 janusec: net/http.(*http2serverConn).runHandler(0xc00084f380, 0xc0000c45c0, 0xc00036c700, 0xc0004180d8)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/h2_bundle.go:5723 +0x8b
Sep 19 12:51:34 server6 janusec: created by net/http.(*http2serverConn).processHeaders
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/h2_bundle.go:5453 +0x505
Sep 19 12:51:34 server6 janusec: 2021/09/19 12:51:34 http2: panic serving 66.249.79.174:57555: interface conversion: interface {} is nil, not *models.CCPolicy
Sep 19 12:51:34 server6 janusec: goroutine 670547 [running]:
Sep 19 12:51:34 server6 janusec: net/http.(*http2serverConn).runHandler.func1(0xc000370458, 0xc000533f8e, 0xc0000a4000)
Sep 19 12:51:34 server6 janusec: /usr/local/go/src/net/http/h2_bundle.go:5716 +0x193
Sep 19 12:51:34 server6 janusec: panic(0xa48040, 0xc0009c9bf0)
Sep 19 12:51:46 server6 systemd: Stopping Janusec Application Gateway...
Sep 19 12:51:46 server6 systemd: Stopped Janusec Application Gateway.
Sep 19 12:51:46 server6 systemd: Started Janusec Application Gateway.

```

Janusec log: 

```
[Janusec] 2021/09/19 00:57:04 GetRPCResponse Do Post "https://server1.domain.com:9443/janusec-admin/api": dial tcp: lookup server1.domain.com on 8.8.8.8:53: read udp 192.160.0.6:54160->8.8.8.8:53: i/o timeout
[Janusec] 2021/09/19 00:57:04 GetRPCResponse Do Post "https://server1.domain.com:9443/janusec-admin/api": dial tcp: lookup server1.domain.com on 8.8.8.8:53: read udp 192.160.0.6:54160->8.8.8.8:53: i/o timeout
[Janusec] 2021/09/19 00:57:04 RPCSelectVulntypes GetResponse Post "https://server1.domain.com:9443/janusec-admin/api": dial tcp: lookup server1.domain.com on 8.8.8.8:53: read udp 192.160.0.6:54160->8.8.8.8:53: i/o timeout
[Janusec] 2021/09/19 00:57:24 GetRPCResponse Do Post "https://server1.domain.com:9443/janusec-admin/api": dial tcp: lookup server1.domain.com on 8.8.8.8:53: read udp 192.160.0.6:41670->8.8.8.8:53: i/o timeout
[Janusec] 2021/09/19 00:57:24 GetRPCResponse Do Post "https://server1.domain.com:9443/janusec-admin/api": dial tcp: lookup server1.domain.com on 8.8.8.8:53: read udp 192.160.0.6:41670->8.8.8.8:53: i/o timeout
[Janusec] 2021/09/19 00:57:24 RPCSelectGroupPolicies GetResponse Post "https://server1.domain.com:9443/janusec-admin/api": dial tcp: lookup server1.domain.com on 8.8.8.8:53: read udp 192.160.0.6:41670->8.8.8.8:53: i/o timeout
[Janusec] 2021/09/19 00:57:44 GetRPCResponse Do Post "https://server1.domain.com:9443/janusec-admin/api": dial tcp: lookup server1.domain.com on 8.8.8.8:53: read udp 192.160.0.6:34210->8.8.8.8:53: i/o timeout
[Janusec] 2021/09/19 00:57:44 GetRPCResponse Do Post "https://server1.domain.com:9443/janusec-admin/api": dial tcp: lookup server1.domain.com on 8.8.8.8:53: read udp 192.160.0.6:34210->8.8.8.8:53: i/o timeout
[Janusec] 2021/09/19 00:57:44 RPCLoadIPPolicies GetResponse Post "https://server1.domain.com:9443/janusec-admin/api": dial tcp: lookup server1.domain.com on 8.8.8.8:53: read udp 192.160.0.6:34210->8.8.8.8:53: i/o timeout
```

Thanks & Best regards !

**Comment by zhyale** [comment]
Please check the server time to make sure the time is correct, and check the network.

**Comment by NgHuuAn** [comment]
Hi, 

We want to restore nftables with command but we got error from your configure, how we can fix it. In case I need whitelist some IP Address, how will I need to do it?

![image](https://user-images.githubusercontent.com/31845795/136364070-c84d06b7-b0bc-4744-892a-4aa82657b579.png)

Thanks !

**Comment by zhyale** [comment]
Hi, you can add IP address policies under the menu of janusec-admin:    WAF Management  -->  IP Policy
